DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS flight_bookings;
DROP TABLE IF EXISTS hotel_bookings;

CREATE TABLE user(
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE flightbookings(
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  departure TEXT NOT NULL,
  arrival TEXT NOT NULL,
  FOREIGN KEY (user_id) REFERENCES user (id)
);

CREATE TABLE hotelbookings(
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  hotel_name TEXT NOT NULL,
  date_start TEXT NOT NULL,
  date_stop TEXT NOT NULL,
  FOREIGN KEY (user_id) REFERENCES user (id)
);
